# Generated by Django 4.1 on 2023-01-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subcatagory_sub_catagory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to='product_item')),
                ('prduct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
