# Generated by Django 4.1 on 2023-01-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_subcatagory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.subcatagory'),
        ),
        migrations.AlterField(
            model_name='product_photo',
            name='prduct_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product'),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='sub_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_catagory', to='product.catagory'),
        ),
    ]
