# Generated by Django 4.1 on 2023-01-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_subcatagory_sub_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product_image'),
            preserve_default=False,
        ),
    ]
