# Generated by Django 4.1 on 2023-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='count',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='price_count',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
