# Generated by Django 4.1 on 2023-01-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_order_deatil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_deatil',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
