# Generated by Django 4.1 on 2023-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_order_deatil_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_deatil',
            name='product_address',
            field=models.TextField(max_length=500),
        ),
    ]
