# Generated by Django 4.1 on 2023-01-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_order_deatil_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_deatil',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
