# Generated by Django 4.1 on 2023-02-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_order_deatil_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_deatil',
            old_name='product_address',
            new_name='order_address',
        ),
    ]
