# Generated by Django 4.1 on 2023-02-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_cotact_number_address_contact_number'),
        ('product', '0022_rename_product_address_order_deatil_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_deatil',
            name='order_address',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order_deatil',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_deatil',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_deatil',
            name='payment_method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_deatil',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_deatil',
            name='total_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_deatil',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
