# Generated by Django 4.1 on 2023-01-13 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_number', models.IntegerField(unique=True)),
                ('profile_photo', models.FileField(upload_to='profile')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField()),
                ('password_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('ODISHA', 'ODISHA'), ('KARNATAKA', 'KARNATAKA'), ('PUNJAB', 'PUNJAB'), ('ANDHRA PRADES', 'ANDHRA PRADESH'), ('ASSAM', 'ASSAM'), ('TAMILNADU', 'TAMILNADU'), ('BIHAR', 'RAJASTAN'), ('DELHI', 'DELHI')], max_length=100)),
                ('pincode', models.IntegerField()),
                ('area', models.TextField()),
            ],
        ),
    ]
