# Generated by Django 4.1 on 2023-01-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_id_alter_address_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
