# Generated by Django 4.1 on 2023-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cotact_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
